[package]
name = "lnk-exe"
version = "0.1.0"
authors = [ "Fintan Halpenny <fintan.halpenny@gmail.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
doctest = true
test = false

[dependencies]
anyhow = "1.0"

[dependencies.clap]
version = "3"
features = [ "derive", "env" ]

[dependencies.librad]
path = "../../librad"

[dependencies.lnk-clib]
path = "../lnk-clib"

[dependencies.lnk-identities]
path = "../lnk-identities"

[dependencies.lnk-profile]
path = "../lnk-profile"

[dependencies.lnk-thrussh-agent]
version = "0.1.0"
default-features = false
