[package]
name = "lnk-clib"
version = "0.1.0"
authors = [ "Fintan Halpenny <fintan.halpenny@gmail.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
doctest = true
test = false

[features]
unsafe = []

[dependencies]
futures-lite = "1.12.0"
once_cell = "1.8"
serde_json = "1.0"
serde = "1.0"
thiserror = "1.0"
tokio = "1.13.1"
tracing = "0.1"

[dependencies.librad]
path = "../../librad"

[dependencies.lnk-thrussh-agent]
version = "0.1.0"
features = [ "tokio-agent" ]

[dependencies.minicbor]
version = ">= 0.9.1, < 0.14"
features = ["std"]
